/*
 * The MIT License
 *
 * Copyright 2020 Universitas Teknologi Yogyakarta.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package arsip.surat.view.panel;

import arsip.surat.model.Petugas;
import arsip.surat.service.PetugasService;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Optional;
import javax.swing.JTable;

/**
 * Panel untuk Menu Petugas
 *
 * @author Muhammad Rosyid Izzulkhaq (rsdiz)
 */
public class PanelMenuPetugas extends javax.swing.JPanel {

    private String selectedPetugas = "";

    private final PetugasService petugasService = PetugasService.getInstance();
    private Thread thread;
    int totalPetugas;
    List<Petugas> listPetugas;

    /**
     * Creates new form PanelMenuPetugas
     */
    public PanelMenuPetugas() {
        initComponents();
        thread = new Thread("thread-petugas") {
            @Override
            public void run() {
                syncListPetugas();
                setModelPetugas();
            }
        };
        startThread();
    }

    private synchronized void syncListPetugas() {
        listPetugas = petugasService.selectAllPetugas();
        totalPetugas = listPetugas.size();
        textTotalPetugas.setText("Total Petugas: " + totalPetugas);
    }

    private int index;

    private synchronized void setModelPetugas() {
        index = 1;
        hideHeaderTable();
        DefaultTableModel modelPetugas = (DefaultTableModel) tabelPetugas.getModel();
        modelPetugas.setRowCount(0);
        listPetugas.forEach(petugas -> {
            Object[] data = new Object[]{
                index,
                petugas.getNama(),
                petugas.getJabatan(),
                petugas.getNama_bidang(),
                petugas.getLevel(),
                petugas.getNip()
            };
            modelPetugas.addRow(data);
            index++;
        });
        tabelPetugas.setModel(modelPetugas);
        tabelPetugas.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getButton() == MouseEvent.BUTTON1) {
                    JTable selected = (JTable) e.getSource();
                    Point point = e.getPoint();
                    int rowSelected = selected.rowAtPoint(point);
                    buttonEdit.setVisible(true);
                    buttonHapus.setVisible(true);
                    selectedPetugas = selected.getModel().getValueAt(rowSelected, 5).toString();
                }
            }
        });
        setTableAlignment(JLabel.CENTER);
    }

    private void startThread() {
        thread.start();
    }

    private void hideHeaderTable() {
        scrollPanelTabelPetugas.getColumnHeader().setVisible(false);
    }

    private void setTableAlignment(int alignment) {
        DefaultTableCellRenderer alignmentRenderer = new DefaultTableCellRenderer();
        alignmentRenderer.setHorizontalAlignment(alignment);
        for (int i = 0; i < tabelPetugas.getColumnModel().getColumnCount(); i++) {
            tabelPetugas.getColumnModel().getColumn(i).setCellRenderer(alignmentRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroupLevel = new javax.swing.ButtonGroup();
        basePanel = new javax.swing.JPanel();
        panelEditPetugas = new javax.swing.JPanel();
        tf_editNama = new javax.swing.JTextField();
        tf_editJabatan = new javax.swing.JTextField();
        tf_editNip = new javax.swing.JTextField();
        tf_editUsername = new javax.swing.JTextField();
        teksLevel = new javax.swing.JTextField();
        tf_panelLevel = new javax.swing.JPanel();
        rb_admin = new javax.swing.JRadioButton();
        rb_petugas = new javax.swing.JRadioButton();
        teksBidang = new javax.swing.JTextField();
        tf_panelBidang = new javax.swing.JPanel();
        cb_editBidang = new javax.swing.JComboBox<>();
        buttonUbahPassword = new javax.swing.JButton();
        buttonKembaliEdit = new javax.swing.JButton();
        separatorEditPetugas = new javax.swing.JSeparator();
        textEditPetugas = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        imgEditPetugas = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        textMenuKelolaPetugas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonRefreshData = new javax.swing.JPanel();
        iconRefreshData = new javax.swing.JLabel();
        textRefreshData = new javax.swing.JLabel();
        buttonTambahData = new javax.swing.JPanel();
        iconTambahData = new javax.swing.JLabel();
        textTambahData = new javax.swing.JLabel();
        buttonInfo = new javax.swing.JPanel();
        iconInfo = new javax.swing.JLabel();
        textInfo = new javax.swing.JLabel();
        panelDaftarPetugas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        headNomer = new javax.swing.JPanel();
        headTextNomor = new javax.swing.JLabel();
        headNama = new javax.swing.JPanel();
        headTextNama = new javax.swing.JLabel();
        headJabatan = new javax.swing.JPanel();
        headTextJabatan = new javax.swing.JLabel();
        headBidang = new javax.swing.JPanel();
        headTextBidang = new javax.swing.JLabel();
        headLevel = new javax.swing.JPanel();
        headTextLevel = new javax.swing.JLabel();
        scrollPanelTabelPetugas = new javax.swing.JScrollPane();
        tabelPetugas = new javax.swing.JTable();
        buttonEdit = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        textTotalPetugas = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(990, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEditPetugas.setBackground(new java.awt.Color(0, 143, 143));
        panelEditPetugas.setPreferredSize(new java.awt.Dimension(990, 460));
        panelEditPetugas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_editNama.setBackground(new java.awt.Color(0, 143, 143));
        tf_editNama.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tf_editNama.setForeground(new java.awt.Color(255, 255, 255));
        tf_editNama.setText("Nama");
        tf_editNama.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Nama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14), new java.awt.Color(150, 255, 255))); // NOI18N
        tf_editNama.setMargin(new java.awt.Insets(2, 10, 2, 10));
        tf_editNama.setNextFocusableComponent(tf_editJabatan);
        panelEditPetugas.add(tf_editNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 290, 60));

        tf_editJabatan.setBackground(new java.awt.Color(0, 143, 143));
        tf_editJabatan.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tf_editJabatan.setForeground(new java.awt.Color(255, 255, 255));
        tf_editJabatan.setText("Jabatan");
        tf_editJabatan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Jabatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14), new java.awt.Color(150, 255, 255))); // NOI18N
        tf_editJabatan.setMargin(new java.awt.Insets(2, 10, 2, 10));
        tf_editJabatan.setNextFocusableComponent(tf_editUsername);
        panelEditPetugas.add(tf_editJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 290, 60));

        tf_editNip.setBackground(new java.awt.Color(0, 143, 143));
        tf_editNip.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tf_editNip.setForeground(new java.awt.Color(255, 255, 255));
        tf_editNip.setText("NIP");
        tf_editNip.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "NIP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14), new java.awt.Color(150, 255, 255))); // NOI18N
        tf_editNip.setMargin(new java.awt.Insets(2, 10, 2, 10));
        tf_editNip.setNextFocusableComponent(tf_editNama);
        panelEditPetugas.add(tf_editNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 290, 60));

        tf_editUsername.setBackground(new java.awt.Color(0, 143, 143));
        tf_editUsername.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tf_editUsername.setForeground(new java.awt.Color(255, 255, 255));
        tf_editUsername.setText("Username");
        tf_editUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14), new java.awt.Color(150, 255, 255))); // NOI18N
        tf_editUsername.setMargin(new java.awt.Insets(2, 10, 2, 10));
        tf_editUsername.setNextFocusableComponent(cb_editBidang);
        panelEditPetugas.add(tf_editUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 290, 60));

        teksLevel.setBackground(new java.awt.Color(0, 143, 143));
        teksLevel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        teksLevel.setForeground(new java.awt.Color(150, 255, 255));
        teksLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        teksLevel.setText("Level");
        teksLevel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelEditPetugas.add(teksLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 257, 50, 20));

        tf_panelLevel.setBackground(new java.awt.Color(0, 143, 143));
        tf_panelLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tf_panelLevel.setPreferredSize(new java.awt.Dimension(270, 40));
        tf_panelLevel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rb_admin.setBackground(new java.awt.Color(0, 143, 143));
        radioGroupLevel.add(rb_admin);
        rb_admin.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        rb_admin.setForeground(new java.awt.Color(255, 255, 255));
        rb_admin.setText("Admin");
        rb_admin.setNextFocusableComponent(rb_petugas);
        tf_panelLevel.add(rb_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 140, 40));

        rb_petugas.setBackground(new java.awt.Color(0, 143, 143));
        radioGroupLevel.add(rb_petugas);
        rb_petugas.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        rb_petugas.setForeground(new java.awt.Color(255, 255, 255));
        rb_petugas.setText("Petugas");
        rb_petugas.setNextFocusableComponent(buttonSimpan);
        tf_panelLevel.add(rb_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, 130, 40));

        panelEditPetugas.add(tf_panelLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 267, 290, 50));

        teksBidang.setBackground(new java.awt.Color(0, 143, 143));
        teksBidang.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        teksBidang.setForeground(new java.awt.Color(150, 255, 255));
        teksBidang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        teksBidang.setText("Bidang");
        teksBidang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelEditPetugas.add(teksBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 157, 50, 20));

        tf_panelBidang.setBackground(new java.awt.Color(0, 143, 143));
        tf_panelBidang.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tf_panelBidang.setPreferredSize(new java.awt.Dimension(270, 40));
        tf_panelBidang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_editBidang.setBackground(new java.awt.Color(0, 143, 143));
        cb_editBidang.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        cb_editBidang.setForeground(new java.awt.Color(255, 255, 255));
        cb_editBidang.setMaximumRowCount(4);
        cb_editBidang.setSelectedIndex(-1);
        cb_editBidang.setBorder(null);
        cb_editBidang.setNextFocusableComponent(rb_admin);
        tf_panelBidang.add(cb_editBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 15, 280, 30));

        panelEditPetugas.add(tf_panelBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 167, 290, 50));

        buttonUbahPassword.setFont(new java.awt.Font("monogram", 0, 24)); // NOI18N
        buttonUbahPassword.setForeground(new java.awt.Color(80, 80, 80));
        buttonUbahPassword.setText("<html><center>UBAH<br>PASSWORD</center></html>");
        buttonUbahPassword.setNextFocusableComponent(buttonKembaliEdit);
        panelEditPetugas.add(buttonUbahPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 130, 50));

        buttonKembaliEdit.setFont(new java.awt.Font("monogram", 0, 28)); // NOI18N
        buttonKembaliEdit.setForeground(new java.awt.Color(0, 103, 103));
        buttonKembaliEdit.setText("<< KEMBALI");
        buttonKembaliEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliEditActionPerformed(evt);
            }
        });
        panelEditPetugas.add(buttonKembaliEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 150, 50));

        separatorEditPetugas.setBackground(new java.awt.Color(0, 133, 133));
        separatorEditPetugas.setForeground(new java.awt.Color(0, 200, 200));
        separatorEditPetugas.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelEditPetugas.add(separatorEditPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 10, 390));

        textEditPetugas.setFont(new java.awt.Font("monogram", 0, 48)); // NOI18N
        textEditPetugas.setForeground(new java.awt.Color(200, 255, 255));
        textEditPetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textEditPetugas.setText("<html>\n<center>\nEDIT<br>PETUGAS\n</center>\n</html>");
        panelEditPetugas.add(textEditPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 90));

        buttonSimpan.setFont(new java.awt.Font("monogram", 0, 36)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(0, 103, 103));
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.setNextFocusableComponent(buttonUbahPassword);
        panelEditPetugas.add(buttonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 130, 50));

        imgEditPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arsip/surat/assets/images/petugas.png"))); // NOI18N
        panelEditPetugas.add(imgEditPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        basePanel.add(panelEditPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 640));
        panelEditPetugas.setVisible(false);

        panelMenu.setBackground(new java.awt.Color(222, 222, 222));
        panelMenu.setPreferredSize(new java.awt.Dimension(990, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textMenuKelolaPetugas.setFont(new java.awt.Font("monogram", 0, 36)); // NOI18N
        textMenuKelolaPetugas.setForeground(new java.awt.Color(0, 51, 51));
        textMenuKelolaPetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textMenuKelolaPetugas.setText("Menu Kelola Petugas");
        panelMenu.add(textMenuKelolaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, 50));
        panelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 890, 10));

        buttonRefreshData.setBackground(new java.awt.Color(232, 232, 232));
        buttonRefreshData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonRefreshData.setPreferredSize(new java.awt.Dimension(100, 100));
        buttonRefreshData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRefreshDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonRefreshDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonRefreshDataMouseExited(evt);
            }
        });
        buttonRefreshData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconRefreshData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon imageIconReload = new ImageIcon(getClass().getResource("/arsip/surat/assets/images/reload.png"));
        Image imgReload = imageIconReload.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        iconRefreshData.setIcon(new ImageIcon(imgReload));
        iconRefreshData.setPreferredSize(new java.awt.Dimension(70, 70));
        buttonRefreshData.add(iconRefreshData, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 70, 70));

        textRefreshData.setFont(new java.awt.Font("Monofonto", 0, 14)); // NOI18N
        textRefreshData.setForeground(new java.awt.Color(0, 51, 102));
        textRefreshData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textRefreshData.setText("Refresh Data");
        textRefreshData.setIconTextGap(0);
        buttonRefreshData.add(textRefreshData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 100, -1));

        panelMenu.add(buttonRefreshData, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 120, 120));

        buttonTambahData.setBackground(new java.awt.Color(232, 232, 232));
        buttonTambahData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonTambahData.setPreferredSize(new java.awt.Dimension(100, 100));
        buttonTambahData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconTambahData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon imageIconAdd = new ImageIcon(getClass().getResource("/arsip/surat/assets/images/add.png"));
        Image imgAdd = imageIconAdd.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        iconTambahData.setIcon(new ImageIcon(imgAdd));
        iconTambahData.setPreferredSize(new java.awt.Dimension(70, 70));
        buttonTambahData.add(iconTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 70, 70));

        textTambahData.setFont(new java.awt.Font("Monofonto", 0, 14)); // NOI18N
        textTambahData.setForeground(new java.awt.Color(0, 51, 102));
        textTambahData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTambahData.setText("Tambah Data");
        textTambahData.setIconTextGap(0);
        buttonTambahData.add(textTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 100, -1));

        panelMenu.add(buttonTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 120, 120));

        buttonInfo.setBackground(new java.awt.Color(232, 232, 232));
        buttonInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonInfo.setPreferredSize(new java.awt.Dimension(100, 100));
        buttonInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon imageIconInfo = new ImageIcon(getClass().getResource("/arsip/surat/assets/images/info.png"));
        Image imgInfo = imageIconInfo.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        iconInfo.setIcon(new ImageIcon(imgInfo));
        iconInfo.setPreferredSize(new java.awt.Dimension(70, 70));
        buttonInfo.add(iconInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 70, 70));

        textInfo.setFont(new java.awt.Font("Monofonto", 0, 14)); // NOI18N
        textInfo.setForeground(new java.awt.Color(0, 51, 102));
        textInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textInfo.setText("Bantuan");
        textInfo.setIconTextGap(0);
        buttonInfo.add(textInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 100, -1));

        panelMenu.add(buttonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 120, 120));

        basePanel.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelDaftarPetugas.setBackground(new java.awt.Color(0, 143, 143));
        panelDaftarPetugas.setPreferredSize(new java.awt.Dimension(990, 460));
        panelDaftarPetugas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headNomer.setBackground(new java.awt.Color(0, 112, 112));
        headNomer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        headNomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headTextNomor.setFont(new java.awt.Font("Monofonto", 0, 18)); // NOI18N
        headTextNomor.setForeground(new java.awt.Color(255, 255, 255));
        headTextNomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headTextNomor.setText("No.");
        headNomer.add(headTextNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jPanel3.add(headNomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 50, 40));

        headNama.setBackground(new java.awt.Color(0, 112, 112));
        headNama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        headNama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headTextNama.setFont(new java.awt.Font("Monofonto", 0, 18)); // NOI18N
        headTextNama.setForeground(new java.awt.Color(255, 255, 255));
        headTextNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headTextNama.setText("Nama");
        headNama.add(headTextNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 20));

        jPanel3.add(headNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 5, 255, 40));

        headJabatan.setBackground(new java.awt.Color(0, 112, 112));
        headJabatan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        headJabatan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headTextJabatan.setFont(new java.awt.Font("Monofonto", 0, 18)); // NOI18N
        headTextJabatan.setForeground(new java.awt.Color(255, 255, 255));
        headTextJabatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headTextJabatan.setText("Jabatan");
        headJabatan.add(headTextJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 20));

        jPanel3.add(headJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 5, 190, 40));

        headBidang.setBackground(new java.awt.Color(0, 112, 112));
        headBidang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        headBidang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headTextBidang.setFont(new java.awt.Font("Monofonto", 0, 18)); // NOI18N
        headTextBidang.setForeground(new java.awt.Color(255, 255, 255));
        headTextBidang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headTextBidang.setText("Bidang");
        headBidang.add(headTextBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel3.add(headBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 5, 200, 40));

        headLevel.setBackground(new java.awt.Color(0, 112, 112));
        headLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        headLevel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headTextLevel.setFont(new java.awt.Font("Monofonto", 0, 18)); // NOI18N
        headTextLevel.setForeground(new java.awt.Color(255, 255, 255));
        headTextLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headTextLevel.setText("Level");
        headLevel.add(headTextLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 20));

        jPanel3.add(headLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 5, 175, 40));

        panelDaftarPetugas.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 20, 900, 50));

        scrollPanelTabelPetugas.setBackground(new java.awt.Color(0, 102, 102));
        scrollPanelTabelPetugas.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tabelPetugas.setBackground(new java.awt.Color(0, 102, 102));
        tabelPetugas.setFont(new java.awt.Font("monogram", 0, 24)); // NOI18N
        tabelPetugas.setForeground(new java.awt.Color(230, 230, 230));
        tabelPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jabatan", "Bidang", "Level", "NIP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPetugas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelPetugas.setGridColor(new java.awt.Color(0, 143, 143));
        tabelPetugas.setRowHeight(50);
        tabelPetugas.setRowMargin(0);
        tabelPetugas.setSelectionBackground(new java.awt.Color(0, 130, 130));
        tabelPetugas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelPetugas.setShowGrid(false);
        tabelPetugas.setShowHorizontalLines(false);
        tabelPetugas.setShowVerticalLines(false);
        tabelPetugas.getTableHeader().setResizingAllowed(false);
        tabelPetugas.getTableHeader().setReorderingAllowed(false);
        scrollPanelTabelPetugas.setViewportView(tabelPetugas);
        tabelPetugas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tabelPetugas.getColumnModel().getColumnCount() > 0) {
            tabelPetugas.getColumnModel().getColumn(0).setResizable(false);
            tabelPetugas.getColumnModel().getColumn(0).setPreferredWidth(60);
            tabelPetugas.getColumnModel().getColumn(1).setResizable(false);
            tabelPetugas.getColumnModel().getColumn(1).setPreferredWidth(250);
            tabelPetugas.getColumnModel().getColumn(2).setResizable(false);
            tabelPetugas.getColumnModel().getColumn(2).setPreferredWidth(190);
            tabelPetugas.getColumnModel().getColumn(3).setResizable(false);
            tabelPetugas.getColumnModel().getColumn(3).setPreferredWidth(200);
            tabelPetugas.getColumnModel().getColumn(4).setResizable(false);
            tabelPetugas.getColumnModel().getColumn(4).setPreferredWidth(160);
            tabelPetugas.getColumnModel().getColumn(5).setResizable(false);
            tabelPetugas.getColumnModel().getColumn(5).setPreferredWidth(0);
        }

        panelDaftarPetugas.add(scrollPanelTabelPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 70, 900, 300));

        buttonEdit.setBackground(new java.awt.Color(0, 112, 112));
        buttonEdit.setFont(new java.awt.Font("monogram", 0, 32)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(0, 143, 143));
        buttonEdit.setText("EDIT");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        panelDaftarPetugas.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 390, 150, 50));
        buttonEdit.setVisible(false);

        buttonHapus.setBackground(new java.awt.Color(0, 112, 112));
        buttonHapus.setFont(new java.awt.Font("monogram", 0, 32)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 0, 51));
        buttonHapus.setText("HAPUS");
        panelDaftarPetugas.add(buttonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 390, 150, 50));
        buttonHapus.setVisible(false);

        textTotalPetugas.setFont(new java.awt.Font("monogram", 0, 24)); // NOI18N
        textTotalPetugas.setForeground(new java.awt.Color(150, 230, 230));
        textTotalPetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTotalPetugas.setText("Total Petugas:");
        panelDaftarPetugas.add(textTotalPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 300, 40));

        basePanel.add(panelDaftarPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        add(basePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRefreshDataMouseEntered
        buttonRefreshData.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_buttonRefreshDataMouseEntered

    private void buttonRefreshDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRefreshDataMouseExited
        buttonRefreshData.setBackground(new Color(232, 232, 232));
    }//GEN-LAST:event_buttonRefreshDataMouseExited

    private void buttonRefreshDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRefreshDataMouseClicked
        if (!thread.isAlive()) {
            thread = new Thread("thread-refresh-petugas") {
                @Override
                public void run() {
                    syncListPetugas();
                    setModelPetugas();
                }
            };
            startThread();
        }
    }//GEN-LAST:event_buttonRefreshDataMouseClicked

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        panelMenu.setPreferredSize(new Dimension(990, 70));
        panelEditPetugas.setVisible(true);
        panelDaftarPetugas.setVisible(false);
        Optional<Petugas> petugas = petugasService.selectPetugasByNIP(selectedPetugas);
        setEditTextField(petugas);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonKembaliEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliEditActionPerformed
        panelMenu.setPreferredSize(new Dimension(990, 250));
        panelEditPetugas.setVisible(false);
        panelDaftarPetugas.setVisible(true);
        setEditTextField();
    }//GEN-LAST:event_buttonKembaliEditActionPerformed

    private void setEditTextField() {
        tf_editJabatan.setText("jabatan");
        tf_editNama.setText("nama");
        tf_editNip.setText("nip");
        tf_editUsername.setText("username");
        radioGroupLevel.clearSelection();
    }

    private void setEditTextField(Optional<Petugas> petugas) {
        tf_editJabatan.setText(petugas.get().getJabatan());
        tf_editNama.setText(petugas.get().getNama());
        tf_editNip.setText(petugas.get().getNip());
        tf_editUsername.setText(petugas.get().getUsername());
        switch (petugas.get().getLevel()) {
            case "admin":
                rb_admin.setSelected(true);
                break;
            case "petugas":
                rb_petugas.setSelected(true);
                break;
            default:
                radioGroupLevel.clearSelection();
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Deklarasi Variabel">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JPanel buttonInfo;
    private javax.swing.JButton buttonKembaliEdit;
    private javax.swing.JPanel buttonRefreshData;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JPanel buttonTambahData;
    private javax.swing.JButton buttonUbahPassword;
    private javax.swing.JComboBox<String> cb_editBidang;
    private javax.swing.JPanel headBidang;
    private javax.swing.JPanel headJabatan;
    private javax.swing.JPanel headLevel;
    private javax.swing.JPanel headNama;
    private javax.swing.JPanel headNomer;
    private javax.swing.JLabel headTextBidang;
    private javax.swing.JLabel headTextJabatan;
    private javax.swing.JLabel headTextLevel;
    private javax.swing.JLabel headTextNama;
    private javax.swing.JLabel headTextNomor;
    private javax.swing.JLabel iconInfo;
    private javax.swing.JLabel iconRefreshData;
    private javax.swing.JLabel iconTambahData;
    private javax.swing.JLabel imgEditPetugas;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDaftarPetugas;
    private javax.swing.JPanel panelEditPetugas;
    private javax.swing.JPanel panelMenu;
    private javax.swing.ButtonGroup radioGroupLevel;
    private javax.swing.JRadioButton rb_admin;
    private javax.swing.JRadioButton rb_petugas;
    private javax.swing.JScrollPane scrollPanelTabelPetugas;
    private javax.swing.JSeparator separatorEditPetugas;
    private javax.swing.JTable tabelPetugas;
    private javax.swing.JTextField teksBidang;
    private javax.swing.JTextField teksLevel;
    private javax.swing.JLabel textEditPetugas;
    private javax.swing.JLabel textInfo;
    private javax.swing.JLabel textMenuKelolaPetugas;
    private javax.swing.JLabel textRefreshData;
    private javax.swing.JLabel textTambahData;
    private javax.swing.JLabel textTotalPetugas;
    private javax.swing.JTextField tf_editJabatan;
    private javax.swing.JTextField tf_editNama;
    private javax.swing.JTextField tf_editNip;
    private javax.swing.JTextField tf_editUsername;
    private javax.swing.JPanel tf_panelBidang;
    private javax.swing.JPanel tf_panelLevel;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
